### PR TITLE
Fix for compatibility issues when CPI is not configured

### LINKED ISSUE #86: CSI configuration is failing if there is no compatible CPI version
**Issue/Feature Description:**
CSI configuration is failing if there is no compatible CPI version even if the user only configured just CSI

**What type of Issue/Feature is this?**
/kind bug fix

**Why this fix/ feature is needed(give scenarios or use cases):**
Unable to just configure CSI if there is no compatible CPI version

**How to reproduce, in case of a bug:**
Make sure there is no compatible CPI version for the cluster(I changed to Kubernetes version) and just configure CSI then VDO will throw errors saying that no compatible CPI version and won't configure CSI.
```
I1028 07:21:20.751922       1 session.go:64] controller-runtime/manager/controller/vdoconfig "msg"="found active cached vSphere client session" "name"="vdo-configca64c175" "namespace"="vmware-system-vdo" "reconciler group"="vdo.vmware.com" "reconciler kind"="VDOConfig" "session"="vcsession" "server"="10.161.136.32"
I1028 07:21:22.347327       1 session.go:106] controller-runtime/manager/controller/vdoconfig "msg"="cached vSphere client session" "name"="vdo-configca64c175" "namespace"="vmware-system-vdo" "reconciler group"="vdo.vmware.com" "reconciler kind"="VDOConfig" "session"="vcsession" "datacenter"="vcqaDC" "server"="10.161.136.32"
I1028 07:21:22.347496       1 vdoconfig_controller.go:1194] controllers/VDOConfig "msg"="vSphere Versions "  "version"=["7.0.3"]
I1028 07:21:22.347531       1 vdoconfig_controller.go:1195] controllers/VDOConfig "msg"="k8s Versions "  "version"="1.21"
E1028 07:21:22.347613       1 vdoconfig_controller.go:1273] controllers/VDOConfig "msg"="Error occurred when fetching the CPI deployment yamls" "error"="could not fetch compatible CPI version for vSphere version and k8s version "  
E1028 07:21:22.347897       1 controller.go:302] controller-runtime/manager/controller/vdoconfig "msg"="Reconciler error" "error"="could not fetch compatible CPI version for vSphere version and k8s version " "name"="vdo-configca64c175" "namespace"="vmware-system-vdo" "reconciler group"="vdo.vmware.com" "reconciler kind"="VDOConfig" 
```

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
Tested on Kind and vanilla Kubernetes clusters

### PR DESCRIPTION
**Pull request by DimpleRajaVamsi**
Fix for compatibility issues when CPI is not configured and there is no compatible version of CPI in the compatible matrix

**What type of PR is this?**
/kind bug fix

**What this PR does / why we need it**:
Fix for compatibility issues when CPI is not configured

**Which issue(s) this PR fixes**:
Fixes #86 

**Test Report Added?**:
/kind TESTED

**Test Report**:
- Added the UT's for the different Positive/Negative Scenarios
- Tested locally on the kind cluster by passing custom compatibility matric where CPI compatible version is not found
```
kosarajud-a02:vsphere-kubernetes-drivers-operator kosarajud$ kubectl describe cm compat-matrix-config -n vmware-system-vdo
Name:         compat-matrix-config
Namespace:    vmware-system-vdo
Labels:       <none>
Annotations:  <none>

Data
====
auto-upgrade:
----
disabled
versionConfigContent:
----
{
    "CSI" : {
             "2.2.1" : {
                    "vSphere" : { "min" : "6.7.1", "max": "7.0.4"},
                    "k8s" : {"min": "1.18", "max": "1.22"},
                    "isCPIRequired" : false,
                    "deploymentPath": [
                    "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.2.1/manifests/v2.2.1/rbac/vsphere-csi-controller-rbac.yaml",
                    "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.2.1/manifests/v2.2.1/rbac/vsphere-csi-node-rbac.yaml",
                    "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.2.1/manifests/v2.2.1/deploy/vsphere-csi-controller-deployment.yaml",
                    "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.2.1/manifests/v2.2.1/deploy/vsphere-csi-node-ds.yaml"]
                    },
            "2.2.0" : {
                    "vSphere" : { "min" : "6.7.1", "max": "7.0.4"},
                    "k8s" : {"min": "1.18", "max": "1.22"},
                    "isCPIRequired" : false,
                    "deploymentPath": [
                    "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.2.0/manifests/v2.2.0/rbac/vsphere-csi-controller-rbac.yaml",
                    "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.2.0/manifests/v2.2.0/rbac/vsphere-csi-node-rbac.yaml",
                    "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.2.0/manifests/v2.2.0/deploy/vsphere-csi-controller-deployment.yaml",
                    "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.2.0/manifests/v2.2.0/deploy/vsphere-csi-node-ds.yaml"]
                    }
        },
    "CPI" : {
            "1.20.0" : {
                    "vSphere" : { "min" : "6.7.1", "max": "7.0.4"},
                    "k8s" : {"skewVersion": "1.22"},
                    "deploymentPath": [
                    "https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/v1.20.0/manifests/controller-manager/cloud-controller-manager-roles.yaml",
                    "https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/v1.20.0/manifests/controller-manager/cloud-controller-manager-role-bindings.yaml",
                    "https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/v1.20.0/manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml"]
                    }
        }
             
}

Events:  <none>
kosarajud-a02:vsphere-kubernetes-drivers-operator kosarajud$ vdoctl configure drivers
Do you want to configure CloudProvider? (Y/N) N
Please provide the vcenter IP for configuring StorageProvider 
VC IP 10.161.136.32
Do you want to establish a secure connection? (Y/N) N
Please provide the credentials for configuring StorageProvider
Username administrator@vsphere.local
Password ********
Datacenter(s) vcqaDC
Do you wish to configure File Volumes? (Y/N) N
Thanks for configuring VDO. The drivers will now be installed.
You can check the status for drivers using `vdoctl status`
kosarajud-a02:vsphere-kubernetes-drivers-operator kosarajud$ kubectl get pods -A | grep csi
kube-system          vsphere-csi-controller-55f949b89-xvpsj       6/6     Running   0          82s
kube-system          vsphere-csi-node-rpxdd                       3/3     Running   0          82s

```

### CODE REVIEW

**Review by aggarwalta — APPROVED** [review]
LGTM, thanks!

**Review by asifdxtreme — APPROVED** [review]
LGTM

File: controllers/vdoconfig_controller_test.go [hunk 1]
```diff
@@ -1374,6 +1374,25 @@ var _ = Describe("TestCheckCompatAndRetrieveSpec", func() {
...
+		It("Should fail with CPI Version not available error", func() {
+			err := r.CheckCompatAndRetrieveSpec(vdoctx, req, vdoConfig, matrixStringIncompatibleCPI)
```
Comment (jvrahav) [inline controllers/vdoconfig_controller_test.go:1387]: if CPI is not configured why are we failing the compat check here.

shouldnt compat check handle this and return successor or say not configured

**Review by jvrahav — CHANGES_REQUESTED** [review]

File: controllers/vdoconfig_controller_test.go (hunk 1 above)
Comment (DimpleRajaVamsi) [reply controllers/vdoconfig_controller_test.go:1387]: In this UT CPI is configured and there is no compatible version so throwing the error. Will change the description a bit so that it will be clear.

**Review by jvrahav — APPROVED** [review]
