### PR TITLE
Fix vdoctl to avoid KUBECONFIG check on invocation of help command

### LINKED ISSUE #70: vdoctl help should not expect kubeconfig argument
**Issue/Feature Description:**

**What type of Issue/Feature is this?**
 /kind bug fix

**Why this fix/ feature is needed(give scenarios or use cases):**
when a user runs vdoctl help, the user should not be prompted to specify kubeconfig argument.

**How to reproduce, in case of a bug:**
Run vdoctl help command

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by ridaz**
**What type of PR is this?**
kind enhancement

**What this PR does / why we need it**:

vdoctl is excepting for KUBECONFIG env variable to be set before user enter any CLI commands.
This PR will allow user to invoke the help command without any pre-requisites ( KUBECONFIG env variable )

**Which issue(s) this PR fixes**:

Fixes #70 

**Test Report Added?**:
kind TESTED

**Test Report**:

```
ridaz@ridaz-a01 vsphere-kubernetes-drivers-operator % unset KUBECONFIG
ridaz@ridaz-a01 vsphere-kubernetes-drivers-operator % bin/vdoctl help
vdoctl is a command line interface for vSphere Kubernetes Drivers Operator.
vdoctl provides the user with basic set of commands required to install and configure VDO.

Usage:
  vdoctl [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  configure   command to configure VDO
  delete      Delete vSphere Kubernetes Driver Operator
  deploy      Deploy vSphere Kubernetes Driver Operator
  help        Help about any command
  status      command to get VDO status
  update      Update the VDO Resources
  version     command to get VDO version

Flags:
      --config string       config file (default is $HOME/.vdoctl.yaml)
  -h, --help                help for vdoctl
      --kubeconfig string   points to the kubeconfig file of the target k8s cluster

Use "vdoctl [command] --help" for more information about a command.
```
vdoctl help

```
ridaz@ridaz-a01 vsphere-kubernetes-drivers-operator % bin/vdoctl help status
This command helps to get the status of the configurations created by VDO.
It includes brief detail about the status of CloudProvider and StorageProvider and Node details

Usage:
  vdoctl status [flags]

Flags:
  -h, --help   help for status

Global Flags:
      --config string       config file (default is $HOME/.vdoctl.yaml)
      --kubeconfig string   points to the kubeconfig file of the target k8s cluster



```

### CODE REVIEW

File: vdoctl/cmd/root.go [hunk 1]
```diff
@@ -102,19 +102,20 @@ func initConfig() {
 		fmt.Fprintln(os.Stderr, "Using config file:", viper.ConfigFileUsed())
 	}
 
-	if len(kubeconfig) <= 0 {
-		kubeconfig = os.Getenv("KUBECONFIG")
+	// Ignore the config check and client creation if help command is invoked
+	if os.Args[1] != "help" {
```
Comment (jvrahav) [inline vdoctl/cmd/root.go:106]: this can be written as 
if os.Args[1] == "help" {
return
}
can you please verify if help for all commands are working without requiring the config for instance
vdoctl deploy
vdoctl delete
vdoctl configure help
vdoctl configure drivers --help

**Review by asifdxtreme — APPROVED** [review]
LGTM

**Review by DimpleRajaVamsi — APPROVED** [review]

**Review by lgayatri — APPROVED** [review]

**Review by aggarwalta — APPROVED** [review]
